spring:
  crss-dataflow:
    datasource:
      jdbcUrl: jdbc:postgresql://localhost:5432/crss_dataflow
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
      maxPoolSize: 20
      connectionTimeout: 10000
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        hbm2ddl:
          import_files:

  # prevent batch job from running on app start
  batch:
    job:
      enabled: false

#liquibase:
#  change-log: classpath:/db/db.changelog-master.xml

server:
  port: 8081
  undertow:
    accesslog:
      dir: target
      enabled: true
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1

#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8082/oauth/access_token
#      userAuthorizationUri: http://localhost:8082/oauth/authorize
#      clientId: crss
#      clientSecret: crsssecret
#      authorized-grant-types: authorization_code,refresh_token,password
#      scope: openid
#      access-token-validity-seconds: 3600
#    resource:
#      userInfoUri: http://localhost:8082/user

logging:
  level:
    com.pemc: DEBUG
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG
    org.apache.http: DEBUG

dataflow:
  url: http://localhost:9393

sftp:
  credentials:
    username: pemc
    password: 123qwe
    host: pemc-storage.southeastasia.cloudapp.azure.com
    port: 22
    workingDirectory: /home/pemc/upload
    privateKey:

# temporary todi-config, to be moved to general config
todi-config:
  dispatch-interval: 5
  max-retry: 2
